10 REM
20 REM
30 REM The unaccompanied violin sonata No. 6 in E major, 1st movement,
40 REM			by Johann Sebastian Bach,
50 REM	faithfully transcribed by Michael Baum for the IBM-PC
60 REM
70 REM Runs 4:06 minutes
80 REM
90 CLS:KEY OFF:SCREEN 0:WIDTH 80
100 COLOR 12:LOCATE 12,23:PRINT"SONATA VI in E Major, 1st Movement
110 COLOR 9: LOCATE 14,35,0:PRINT"J.S. BACH
120 A$="g#eg#e":B$="g#eg#d#":C$="g#eg#d":D$="o4aeac#":E$="o4aeao3b"
130 F$="o4g#eg#o3b":G$="o4g#eg#o3a":H$="o4f#ef#o3a":I$="o4f#ef#o3g#"
140 J$="o4eeeo3g#":K$="o4eeeo3f#":L$="o4d#ed#o3f#"
150 M$="o4c#o3ao4c#o3a":N$="o4c#o3ao4c#o3g#":O$="o4c#o3ao4c#o3g"
160 P$="o4do3ao4do3f#":Q$="o4do3ao4do3e":R$="O4C#O3AO4C#O3E"
170 S$="o4c#o3ao4c#o3d":T$="o3babd":U$="o3babc#":V$="o3aaac#"
180 W$="o3aaao2b":X$="o3g#ag#o2b"
190 PLAY "t100msp8o5l16ED#l8eo4bg#b l16ef#ed#l8eo3bg#b mll16ebf#bg#babg#bf#b eo4ed#c#o3bo4ed#c#o3bag#f#
200 PLAY "msl16ebf#bg#babg#bf#b eo4ed#c#o3bo4ed#c#o3bag#f#
210 PLAY"mlef#g#abo4c#d#ef#g#af# g#bef#g#abo5c#d#ec#d# eo4babg#babg#bf#b eo5ed#c#o4beo5c#o4ebeae
220 PLAY"ms g#bf#bg#babg#bf#b eo5ed#c#o4beo5c#o4ebeae
230 PLAY "mn g#eeed#eeef#ed#e eeg#ef#eg#eaef#e
240 PLAY "ms g#eeed#eeef#ed#e eeg#ef#eg#eaef#e
250 A$="g#eg#e
260 PLAY "xa$;xa$;xa$;xb$;xb$;xb$;xc$;xc$;xc$;xd$;xd$;xd$;xe$;xe$;xe$;
270 PLAY "xf$;xf$;xf$;xg$;xg$;xg$;xh$;xh$;xh$;xi$;xi$;xi$;xj$;xj$;xj$;
280 PLAY "xk$;xk$;xk$;xl$;xl$;xl$;
290 PLAY "mlef#ef#g#bef#g#bef# g#ag#abo4eo3g#abo4eo3g#a bo4c#o3bo4c#dg#o3bo4c#dg#o3bo4c#
300 PLAY "dbg#edo3bg#edc#do2b
310 PLAY "o3c#d#c#d#fg#c#d#fg#c#d# ff#ff#g#o4c#o3ff#g#o4c#o3ff#
320 PLAY "g#ag#abo4fo3g#abo4fo3g#a bo4g#fc#bg#af#fg#c#o3b
330 PLAY "ao4c#o3af#o4f#d#ec#cd#o3g#f# eg#ec#eg#o4c#o3g#o4ec#g#c#
340 PLAY"cd#co3g#o4g#gg#gg#d#ec# cd#co3g#o4f#ff#ff#d#ec#
350 PLAY "cd#co3g#ag#ag#ad#ec# cf#c#f#d#f#c#f#cf#d#f# o2g#o3f#o4d#o3f#o4co3f#o4d#o3f#o4co3f#o4d#o3f#
360 PLAY "o2g#o3eo4c#o3eo4eo3eo4c#o3eo4eo3eo4c#o3e
370 PLAY "o2g#o3f#o4d#o3f#o4co3f#o4d#o3f#o4co3f#o4d#o3f#
380 PLAY "o2g#o3eo4c#o3eo4eo3eo4c#o3eo4eo3eo4c#o3e
390 PLAY "o2g#o3go4c#o3go4eo3go4c#o3go4eo3go4c#o3g
400 PLAY "o2g#o3go4c#o3go4eo3go4c#o3go4eo3go4c#o3g
410 PLAY "o2g#o3g#o4c#o3g#o4d#o3g#o4c#o3g#o4d#o3g#o4c#o3g#
420 PLAY "o2g#o3f#o4co3f#o4d#o3f#o4co3f#o4d#o3f#o4co3f#
430 PLAY "c#o4c#o3bag#o4c#o3g#f#eg#ed# c#o4c#o3g#f#eg#ed#c#ec#o2b
440 PLAY "o2a#o3f#o4c#o3f#o4eo3f#o4c#o3f#o4eo3f#o4c#o3f#
450 PLAY "o2a#o3f#o4eo3f#o4c#o3f#o4eo3f#o4c#o3f#o4eo3f#
460 PLAY "o2bo4ba#g#f#bf#ed#f#d#c# o3bo4bf#ed#f#d#c#o3bo4d#o3ba
470 PLAY "o3g#o4dedg#dbdg#ded o3g#o4dedo3g#o4do3f#o4do3g#o4do3eo4d
480 PLAY "o4c#eag#aedec#eo3bo4e o3ao4ag#f#eo3ao4f#o3ao4eo3ao4do3a
490 PLAY "mso4c#eo3bo4ec#edec#eo3bo4e o3ao4ag#f#eo3ao4f#o3ao4eo3ao4do3a
500 PLAY "mno4c#o3aaag#aaabag#a aao4c#o3abao4c#o3ao4do3aba
510 PLAY "mso4c#o3aaag#aaabag#a aao4c#o3abao4c#o3ao4do3aba
520 '
530 PLAY "xm$;xm$;xm$;xn$;xn$;xn$;xo$;xo$;xo$;xp$;xp$;xp$;
540 PLAY "xq$;xq$;xq$;xr$;xr$;xr$;xs$;xs$;xs$;xt$;xt$;xt$;
550 PLAY "xu$;xu$;xu$;xv$;xv$;xv$;xw$;xw$;xw$;xx$;xx$;xx$;
560 PLAY "ml ababo3c#eo2abo3c#eo2ab o3c#dc#deac#deac#d ef#ef#go4c#o3ef#go4c#o3ef#
570 PLAY "go4ec#dec#o3a#bo4c#o3a#f#e dc#o2bo3c#df#o2bo3c#df#o2bo3c#
580 PLAY "dedef#bdef#bde f#g#f#g#ao4d#o3f#g#ao4d#o3f#g#
590 PLAY "ao4f#d#ef#d#cc#d#co3g#f# fo4bg#abg#ff#g#fc#o3b ao5c#o4abo5c#o4af#g#af#dc#
600 PLAY "o3bo5do4bo5c#do4bg#abg#fg# c#d#c#d#fg#c#d#fg#c#d# ff#ff#g#bff#g#bff#
610 PLAY "g#ag#abo5do4g#abo5do4g#a bo5do4bg#fbg#fc#bag# f#g#af#o3bo4ag#f#c#g#f#f
620 PLAY "def#do3g#o4f#edo3a#o4edc# o3bo4c#do3bfo4dc#o3bf#o4c#o3ba
630 PLAY "g#abag#babg#bf#b ff#g#abfo4do3fo4c#o3fbf f#af#c#o2ao3c#f#c#ac#f#c#
640 PLAY "fg#fc#fg#o4c#o3g#o4fc#g#o3b ao4c#o3af#ao4c#f#c#af#o5c#o4f#
650 PLAY "fg#fc#o5c#cc#cc#o4g#af# fg#fc#ba#ba#bg#af#
660 PLAY "fg#fc#dc#dc#do3g#af# fg#o4c#mnbbmlg#af#fg#c#o3b ao4c#f#o5mnc#c#mlo4abg#f#adc#
670 PLAY "o3bo4do3gf#fg#c#o2bao3c#f#g# af#bf#o4c#o3f#o4do3f#c#f#g#f
680 PLAY "f#ag#mnaaamlg#af#aea d#aeaf#ag#mnaaamlf#a g#ag#f#eo4ed#ec#eo3bo4e
690 PLAY "o3a#o4eo3bo4ec#ed#mneeemlc#e d#ed#c#o3bo4c#d#ef#g#af#
700 PLAY "bo3babg#bf#bebdb c#ef#g#abo4c#def#g#e o4ao3ag#af#aead#ac#a
710 PLAY "o2bo3d#ef#g#abo4c#d#ef#d# g#o3edec#eo2bo3eo2ao3eo2g#o3e
720 PLAY "o2ao3eo4c#o3bo4c#eag#af#c#e o2bo3f#o4d#c#d#f#ag#af#d#f#
730 PLAY "o2bo3g#babo4eg#f#g#eo3bo4e o2bo3a#o4c#o3bo4c#ea#g#a#ec#e
740 PLAY "d#ba#g#f#bf#ed#f#d#c# o3bo4bag#f#af#ed#f#d#c# o3bo4ag#f#eg#ed#c#ec#o3b
750 PLAY "ao4g#f#ed#f#d#c#o3bo4d#o3ba g#o4ec#o3bao4c#o3ag#f#af#e
760 PLAY "d#f#ao4c#o3bo4d#f#g#ag#af# g#eg#bo5eo4bg#eo3bo4eo5ed#
770 PLAY "eo4bg#edec#edeo3bo4e c#eaec#eo3bo4ec#eo3ao4e
780 PLAY "o3bo4eg#eo3bo4eo3ao4eo3bo4eo3g#o4e o3ao4ef#ed#mneeemlf#eg#e
790 PLAY "a4.b8g#4
800 PLAY "mno2l16ao4ag#l32af#f#g#f#g#f#g#f#g#f#g#f#g#l8e
810 PLAY "l16eo5ed#c#o4bo5eo4ao5eo4g#o5eo4f#o5e o4eed#c#o3bo4eo3ao4eo3g#o4eo3f#o4e
820 PLAY" mbmlt90o3eg#bo4d#t80eg#t70bo5d#t60l8e
830  PI=3.14159
840 SCREEN 1,0:COLOR 0,1
850 FOR I=50 TO 130 STEP 20
860 LINE(20,I)-(300,I)
870 NEXT
880 CIRCLE(32,70),4,2,,,1:PAINT(32,70),2
890 CIRCLE(48,70),20,2,0,PI,1
900 CIRCLE(48,70),19,2,0,PI,1
910 CIRCLE(25,70),53,2,3*PI/2,0,1.2
920 CIRCLE(25,70),52,2,3*PI/2,0,1.2
930 CIRCLE(74,60),2,2,,,1
940 CIRCLE(74,80),2,2,,,1
950 PAINT(74,80),2:PAINT(74,60),2
960 LINE(82,75)-(82,120),2
970 DRAW "bm82,107"
980 DRAW "e3rer3f3d6g4lglglgl
990 PAINT (84,115),2
1000 LINE(105,90)-(118,84),2,BF
1010 CIRCLE(140,40),11,1
1020 LINE(129,40)-(129,110),1
1030 LINE(160,50)-(160,130),3
1040 CIRCLE(183,50),11,1
1050 LINE(172,50)-(172,120),1
1060 CIRCLE(220,30),11,1:LINE(200,30)-(240,30),3
1070 LINE(209,30)-(209,100),1
1080 LINE(230,50)-(230,130)
1090 LINE(246,30)-(246,50),2
1100 LINE(246,40)-(256,36),2:LINE-(256,60),2
1110 LINE(246,50)-(256,46),2
1120 CIRCLE(275,40),11,1:LINE(264,40)-(264,110),1
1130 CIRCLE(294,40),2,1
1140 PAINT(275,40),1:PAINT(294,40),1
1150 LOCATE 18,10:PRINT"A Musical Riddle from "
1160 LOCATE 20,10:PRINT"The Art of the Fugue!"
1170 LOCATE 22,9:PRINT"(Sprechen zie Deutsch?)
