//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VTerm.rc
//
#define IDB_MINICONNEXION               2
#define IRR_WINSOCK                     2
#define IDC_AVANCE                      3
#define IDC_CLEAR_RECENT                4
#define IDD_ABOUTBOX                    100
#define CG_IDR_POPUP_VTERM_VIEW         102
#define CG_IDS_PHYSICAL_MEM             103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_STATUS_CONNEXION             107
#define ID_COORDONNEES_CURSEUR          108
#define ID_CODAGE_8BITS                 109
#define IDS_VERSION                     110
#define IDR_MAINFRAME                   128
#define IDR_VTERMTYPE                   129
#define IDD_ABOUT_WINSOCK               130
#define IDR_WINSOCK                     130
#define IDD_REMOTE_HOST                 131
#define IDD_OPTIONS                     132
#define IDD_STATS                       133
#define IDD_COULEURS                    134
#define IDB_CONNEXION                   135
#define IDR_CONNEXION                   136
#define IDB_CONNEXION1                  136
#define IDR_MINICONNEXION               137
#define IDR_RT_MANIFEST1                138
#define IDC_LBL_VERSION                 1000
#define IDC_TXT_VERSION                 1001
#define IDC_LBL_DESCRIPTION             1002
#define IDC_TXT_DESCRIPTION             1003
#define IDC_LBL_SYSSTAT                 1004
#define IDC_TXT_HOST                    1004
#define IDC_TXT_SYSSTAT                 1005
#define IDC_RENDUBRILLANT               1005
#define IDC_LBL_MAXSOCKETS              1006
#define IDC_RENDUGRAS                   1006
#define IDC_TXT_MAXSOCKETS              1007
#define IDC_LBL_MAXUDPDG                1008
#define IDC_TEXTOUTLENLIST              1008
#define IDC_TXT_MAXUDPDG                1009
#define IDC_LBL_VERSION2                1010
#define IDC_LONGMOY                     1011
#define IDC_TXT_HIGHVERSION             1011
#define IDC_NBDESSINECELLULE            1012
#define IDC_RAZSTATS                    1013
#define IDC_NBONDRAW                    1014
#define IDC_NBINVALIDATERECT            1015
#define IDC_RESTAURER                   1015
#define IDC_NBONUPDATE                  1016
#define IDC_BCBLEU                      1016
#define IDC_NBONUPDATECELLULE           1017
#define IDC_BCBLEU_BRILLANT             1017
#define IDC_NBTEXTOUT                   1018
#define IDC_BCNOIR                      1018
#define IDC_BCNOIR_BRILLANT             1019
#define IDC_HOST1                       1019
#define IDC_M_X                         1019
#define IDC_BCVERT                      1020
#define IDC_HOST2                       1020
#define IDC_M_Y                         1020
#define IDC_BCVERT_BRILLANT             1021
#define IDC_M_CX                        1021
#define IDC_HOST4x                      1021
#define IDC_HOST4                       1021
#define IDC_BCCYAN                      1022
#define IDC_M_CY                        1022
#define IDC_HOST5x                      1022
#define IDC_HOST5                       1022
#define IDC_BCCYAN_BRILLANT             1023
#define IDC_PHYSICAL_MEM                1023
#define IDC_HOST7                       1023
#define IDC_BCROUGE                     1024
#define IDC_HOST6                       1024
#define IDC_BCROUGE_BRILLANT            1025
#define IDC_HOST3x                      1025
#define IDC_HOST3                       1025
#define IDC_BCMAGENTA                   1026
#define IDC_AUTOLOGIN                   1026
#define IDC_BCMAGENTA_BRILLANT          1027
#define IDC_TXT_LOGIN                   1027
#define IDC_BCJAUNE                     1028
#define IDC_TXT_PASSWORD                1028
#define IDC_COD8OEM                     1028
#define IDC_BCJAUNE_BRILLANT            1029
#define IDC_TXT_TERMINAL                1029
#define IDC_COD8ANSI                    1029
#define IDC_BCBLANC                     1030
#define IDC_TXT_PORT                    1030
#define IDC_HOST6x                      1030
#define IDC_TDANSI                      1030
#define IDC_BCBLANC_BRILLANT            1031
#define IDC_HOST9                       1031
#define IDC_TDANSIM                     1031
#define IDC_TDANSIW                     1032
#define IDC_NOESCV                      1033
#define IDC_IDENTMAN                    1034
#define IDC_128128                      1035
#define IDC_ADRCLIENT                   1036
#define IDC_NORECENT                    1037
#define IDC_POINTPN                     1037
#define IDC_VERSION                     1038
#define IDC_LIGNES                      1039
#define IDC_COLONNES                    1040
#define IDC_HOST8                       1041
#define IDS_RETRYCONNECT                32100
#define ID_ABOUT_SOCKETS                32771
#define ID_ABOUT_WINSOCK                32772
#define ID_NEXT_WINDOW                  32774
#define ID_POLICE                       32775
#define ID_OPTIONS                      32776
#define ID_TESTMIRE                     32778
#define ID_STATS                        32780
#define ID_TESTPERFORMANCES             32781
#define ID_TESTDEFILEMENT               32782
#define ID_COULEURS                     32783
#define ID_EDIT_COPY_RECT               32785
#define ID_RESTAURE                     32786
#define ID_EDIT_COPY_PASTE              32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
