/*  COULEURS.H	P.Violent	MSC 4.0|5.0 / MS-DOS
**
**  Ver. 1.00	1.VII.87
**  Ver. 1.01	9.VII.87	Clignotant avec 1 t
**  Ver. 1.10	13.X.87 	Version remani‚e
**  Ver. 2.00	13.X.87 	E/S ‚volu‚es
**
**  D‚claration de constantes de couleurs pour C Microsoft
**  Les codes sont compatibles GWBASIC et TURBO PASCAL, mais pas ANSI, d'o—
**  le tableau de conversion de COULEURS.C...
*/

#define NOIR   0
#define BLEU   1
#define VERT   2
#define CYAN   3
#define ROUGE  4
#define VIOLET 5
#define JAUNE  6
#define BLANC  7

#define BRILLANT    0x08
#define CLIGNOTANT  0x80
#define SOULIGNE    0x10

