Aide
Cette
Choisissez l
Cliquez sur l
Fenêtre d'à propos
Fenêtre principale
Fichier
GENMUL
Le programme GENMUL pe
Les menus
Sommaire
affiche
aide
commande
contient
copyright
d'utilisation
dans
des
disque
disquettes
d’installation
fenêtre
fichiers
générateur
génération
l'aide
menu
modules
mémoire
numéro
ordinateur.
permet
pour
principale
programme
progressi
propos
présente
répertoire
sur
une
version
votre
vous
