// serieec.h
// Interface publique E-SQL/C

#include <esqlc.h>
#include <datetime.h>

#include <t_dilution.h>
#include <t_critere.h>
#include <t_criterel.h>
#include <t_germelabo.h>
#include <t_serielabo.h>
#include <t_seriedetail.h>
#include <t_serieboite.h>
#include <t_produit.h>

$struct T_DILUTION		r_dil;
$struct T_CRITERE		r_cri;
$struct T_GERMELABO		r_gl;
$struct T_SERIELABO		r_ser;
$struct T_SERIEDETAIL	r_sd;
$struct T_SERIEBOITE	r_sb;
$struct T_PRODUIT		r_pro;
