VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "etbFim"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public numetb As String
Public numsec As Integer
Public préfixe As String
Public nom As String
Public nombase As String
Public adr1 As String
Public adr2 As String
Public cpost As String
Public bdist As String
Public corresp As String
Public tel As String
Public telex As String
Public fax As String
Public grille As String
Public pays As Integer
