// paires.h
// Tableau de codage des 100 paires les plus fréquentes 
// dans les mots du dictionnaire
// PV 13/05/94
//
// Codage des caractères en PC-8

#define NBP 100

char tP[NBP][3] =
{ "ta", "nt", "er", "ua", "ra", "on", "en", "ai", "is", "es",
  "re", "fa", "an", "ie", "te", "ri", "ns", "se", "ro", "sa",
  "ti", "ss", "‚a", "in", "d‚", "it", "ez", "le", "ou", "as",
  "io", "co", "li", "la", "ur", "ar", "ba", "ch", "il", "ne",
  "ll", "al", "tr", "at", "r‚", "qu", "ma", "or", "na", "ue",
  "me", "nn", "ca", "st", "ir", "‚e", "ni", "pa", "di", "si",
  "em", "lo", "‚c", "ge", "‚s", "eu", "nc", "to", "ac", "ul",
  "ts", "de", "ha", "ui", "po", "nd", "‚r", "ag", "ol", "us",
  "pr", "om", "so", "fi", "ve", "mi", "ot", "‡a", "ci", "bo",
  "ja", "ce", "au", "t‚", "am", "pe", "ap", "mo", "ut", "ic",
};

