VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FRT"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Classe FRT
' Modélise une FRT
' 14/05/1998 PV

Option Explicit

Public indice As Long
Public opersais As Integer
Public datesais As Date
Public operimpr
Public tsimpr
Public timestamp As Date
