//==================================
// TASKWIND.H - Matt Pietrek 1993
//==================================
#define IDT_TASKINFO_HTASK      100
#define IDT_TASKINFO_NAME       100
#define IDT_TASKINFO_HINSTANCE  101
#define IDT_TASKINFO_HMODULE    102
#define IDT_TASKINFO_PARENT     103
#define IDT_TASKINFO_DIRECTORY  104
#define IDT_TASKINFO_CMDLINE    105
#define IDB_TASKINFO            109
#define IDB_TASK_TERMINATE      110
#define IDB_WM_CLOSE            104
#define IDL_TASKS               101
#define IDL_WINDOWS             102
#define IDB_SWITCHTO            103
#define IDB_CANCEL              105
#define IDB_CASCADE             106
#define IDB_TILE                107
#define IDB_ARRANGEICONS        108
